Norwegian translations added again
emsesp/EMS-ESP32 pull request #1138
Opened 2023-03-22 14:40 UTC by Vikingn

Now I think I have understand how to do this !

Does it look nice now ?

2023-03-22 15:10 UTC, MichaelDvP commented
Yes, now it's the right base. I think you have also made changes to the web index.ts, please add this file. And in line 119 for "secondes" you have edited the column of pl-language.

2023-03-22 15:32 UTC, Vikingn commented
Fixed line 119  Used Google translate for the polish seconds I have just edited this file

2023-03-22 15:41 UTC, Vikingn commented
Hi !

Can you look at it now ?

It should just be the locale_translations.h file.

I have changed line 119 so the polish should be right too.

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: ***@***.***>
Sendt: onsdag 22. mars 2023 kl. 16.10
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [emsesp/EMS-ESP32] Norwegian translations added again (PR #1138)


Yes, now it's the right base. I think you have also made changes to the web index.ts, please add this file. And in line 119 for "secondes" you have edited the column of pl-language.

—
Reply to this email directly, view it on GitHub<https://github.com/emsesp/EMS-ESP32/pull/1138#issuecomment-1479747675>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AISYX5VJUZKN2DK7LETZJALW5MI7XANCNFSM6AAAAAAWD5I6KE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-03-22 16:04 UTC, MichaelDvP requested changes
I've commented in the changes. Rest looks good.

2023-03-22 16:09 UTC, Vikingn commented
Hi !

Sekund was it before I edited it now.

Google translate say Sekundy

I thaught something was wrong from line 271, and asked proddy.. took some days and I missed to add those back.

Should I fix those lines or do you do it ?



Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: ***@***.***>
Sendt: onsdag 22. mars 2023 kl. 17.04
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [emsesp/EMS-ESP32] Norwegian translations added again (PR #1138)


@MichaelDvP requested changes on this pull request.

I've commented in the changes. Rest looks good.


In src/locale_translations.h<https://github.com/emsesp/EMS-ESP32/pull/1138#discussion_r1145051325>:

> @@ -116,19 +116,19 @@ MAKE_WORD_TRANSLATION(OFF, "OFF", "AUS", "UIT", "AV", "wył.", "AV", "OFF", "KAP

 MAKE_WORD_TRANSLATION(minutes, "minutes", "Minuten", "Minuten", "Minuter", "minut", "Minutter", "minutes", "dakika")

 MAKE_WORD_TRANSLATION(hours, "hours", "Stunden", "Uren", "Timmar", "godzin", "Timer", "heures", "saat")

 MAKE_WORD_TRANSLATION(days, "days", "Tage", "Dagen", "Dagar", "dni", "Dager", "jours", "gün")

-MAKE_WORD_TRANSLATION(seconds, "seconds", "Sekunden", "Seconden", "Sekunder", "sekund", "Sekunder", "secondes", "saniye")

+MAKE_WORD_TRANSLATION(seconds, "seconds", "Sekunden", "Seconden", "Sekunder", "sekundy", "Sekunder", "secondes", "saniye")

i think the old pl-translation was correct: "sekund"


In src/locale_translations.h<https://github.com/emsesp/EMS-ESP32/pull/1138#discussion_r1145054826>:

> @@ -268,487 +268,487 @@ MAKE_WORD_TRANSLATION(cyl2, "cyl 2", "Zyl_2", "Cil 2", "Cyl 2", "cyl 2", "cyl 2"



 // Entity translations

 // Boiler

-MAKE_TRANSLATION(wwtapactivated, "wwtapactivated", "turn on/off", "Durchlauferhitzer aktiv", "zet aan/uit", "på/av", "system przygotowywania", "slå på/av", "ecs activée")

-MAKE_TRANSLATION(reset, "reset", "Reset", "Reset", "Reset", "Nollställ", "kasowanie komunikatu", "nullstill", "reset")

-MAKE_TRANSLATION(oilPreHeat, "oilpreheat", "oil preheating", "Ölvorwärmung", "Olie voorverwarming", "Förvärmning olja", "podgrzewanie oleju", "oljeforvarming", "préchauffage de l'huile")

-MAKE_TRANSLATION(heatingActive, "heatingactive", "heating active", "Heizen aktiv", "Verwarming actief", "Uppvärmning aktiv", "c.o. aktywne", "oppvarming aktiv", "chauffage actif")

-MAKE_TRANSLATION(tapwaterActive, "tapwateractive", "tapwater active", "Warmwasser aktiv", "Warm water actief", "Varmvatten aktiv", "c.w.u. aktywne", "varmtvann aktiv", "eau chaude active")

for these lines 271-275 you have removed the en-fullname, not good.

—
Reply to this email directly, view it on GitHub<https://github.com/emsesp/EMS-ESP32/pull/1138#pullrequestreview-1352967852>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AISYX5VOJV5ZS6EK5YNTXEDW5MPJ3ANCNFSM6AAAAAAWD5I6KE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-03-22 16:11 UTC, Vikingn commented on src/locale_translations.h
> +MAKE_WORD_TRANSLATION(seconds, "seconds", "Sekunden", "Seconden", "Sekunder", "sekundy", "Sekunder", "secondes", "saniye")
sekund is norwegian for 1 second. sekundy is seconds in polish say google translate

2023-03-22 16:17 UTC, MichaelDvP commented
> Should I fix those lines or do you do it ?

After all, you are only 6 lines away  from a successful PR, i think now bring it to the good end.

2023-03-22 16:18 UTC, Vikingn commented
I do the lines now



Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: ***@***.***>
Sendt: onsdag 22. mars 2023 kl. 17.17
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [emsesp/EMS-ESP32] Norwegian translations added again (PR #1138)


Should I fix those lines or do you do it ?

After all, you are only 6 lines away from a successful PR, i think now bring it to the good end.

—
Reply to this email directly, view it on GitHub<https://github.com/emsesp/EMS-ESP32/pull/1138#issuecomment-1479872105>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AISYX5UZOZG3KJU7CT5GJOTW5MQ3HANCNFSM6AAAAAAWD5I6KE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-03-22 16:25 UTC, Vikingn commented
Edited the file again fixed line 271-275

2023-03-22 16:39 UTC, MichaelDvP commented on src/locale_translations.h
> +MAKE_WORD_TRANSLATION(seconds, "seconds", "Sekunden", "Seconden", "Sekunder", "sekundy", "Sekunder", "secondes", "saniye")
Afair pl translation is made by @pswid  I think as native speaker he knows better than google translate. Or, if this is wrong, he will correct it.

2023-03-22 16:44 UTC, Vikingn commented
Hi !
It was strange, because you said polish was wrong, and now you want it back to what it was ?

I think maybe I could have changed it by a mistake before.

I think an easy Word as Seconds should be right in Google Translate.

But do as you want ! Im shure that the polish person know polish much better than me.

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: ***@***.***>
Sendt: onsdag 22. mars 2023 kl. 17.39
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [emsesp/EMS-ESP32] Norwegian translations added again (PR #1138)


@MichaelDvP commented on this pull request.


In src/locale_translations.h<https://github.com/emsesp/EMS-ESP32/pull/1138#discussion_r1145122304>:

> @@ -116,19 +116,19 @@ MAKE_WORD_TRANSLATION(OFF, "OFF", "AUS", "UIT", "AV", "wył.", "AV", "OFF", "KAP

 MAKE_WORD_TRANSLATION(minutes, "minutes", "Minuten", "Minuten", "Minuter", "minut", "Minutter", "minutes", "dakika")

 MAKE_WORD_TRANSLATION(hours, "hours", "Stunden", "Uren", "Timmar", "godzin", "Timer", "heures", "saat")

 MAKE_WORD_TRANSLATION(days, "days", "Tage", "Dagen", "Dagar", "dni", "Dager", "jours", "gün")

-MAKE_WORD_TRANSLATION(seconds, "seconds", "Sekunden", "Seconden", "Sekunder", "sekund", "Sekunder", "secondes", "saniye")

+MAKE_WORD_TRANSLATION(seconds, "seconds", "Sekunden", "Seconden", "Sekunder", "sekundy", "Sekunder", "secondes", "saniye")

Afair pl translation is made by @pswid<https://github.com/pswid> I think as native speaker he knows better than google translate. Or, if this is wrong, he will correct it.

—
Reply to this email directly, view it on GitHub<https://github.com/emsesp/EMS-ESP32/pull/1138#discussion_r1145122304>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AISYX5S5ZJJDO2L3GBJ27P3W5MTNDANCNFSM6AAAAAAWD5I6KE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-03-23 19:37 UTC, proddy commented
this is still missing the index.ts file @Vikingn

2023-03-23 20:34 UTC, Vikingn commented
Why do I need to send that file ? I dont think I have changed that file
It look like this:
export * from './ap';
export * from './features';
export * from './me';
export * from './mqtt';
export * from './ntp';
export * from './security';
export * from './signin';
export * from './system';
export * from './network';

2023-03-23 20:47 UTC, proddy commented
I meant the web translations from `\interface\src\i18n\no\index.ts`  like the fix for Days

2023-03-23 21:12 UTC, Vikingn commented
Tranlated what was missing and created a new PR 1140

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: ***@***.***>
Sendt: torsdag 23. mars 2023 kl. 21.48
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [emsesp/EMS-ESP32] Norwegian translations added again (PR #1138)


I meant the web translations from \interface\src\i18n\no\index.ts like the fix for Days

—
Reply to this email directly, view it on GitHub<https://github.com/emsesp/EMS-ESP32/pull/1138#issuecomment-1481876242>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AISYX5WNA4K6GOK7CT3MUX3W5SZH5ANCNFSM6AAAAAAWD5I6KE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-03-24 11:13 UTC, merged

2023-03-24 11:52 UTC, Vikingn commented
Good, I can send the inder file later today

Sendt fra min iPhone

24. mar. 2023 kl. 12:14 skrev Proddy ***@***.***>:

﻿

Merged #1138<https://github.com/emsesp/EMS-ESP32/pull/1138> into dev.

—
Reply to this email directly, view it on GitHub<https://github.com/emsesp/EMS-ESP32/pull/1138#event-8837505777>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AISYX5RFLIJK4HJS5SJ7LALW5V6X7ANCNFSM6AAAAAAWD5I6KE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>