autodetect, download and install firmware upgrades
emsesp/EMS-ESP32 pull request #1969
Opened 2024-08-29 11:58 UTC by proddy

Further improvements. Now the Download page will check if there is an updated firmware available (for dev or stable depending on which branch you are on). And give the user to download and install automatically.

There is also the option to switch from the Stable branch to the Dev branch (but no way back).

Seems to work on my setup.

2024-08-29 12:09 UTC, proddy commented
And @MichaelDvP I got the same Network Error when uploading using the DragNDrop so will try and fix that too next

2024-08-30 09:04 UTC, MichaelDvP requested changes
A lot of changes. I have not checked all.
Appart from the not working log i've found: (not part of this PR)
- the divider in settings, is it intended? https://github.com/proddy/EMS-ESP32/blob/41ec9162fda52b033a4202f459a7c3ad75e506f3/interface/src/app/settings/Settings.tsx#L134
- custom entity adding/editing is still reversed by autoupdate. In this line https://github.com/proddy/EMS-ESP32/blob/41ec9162fda52b033a4202f459a7c3ad75e506f3/interface/src/app/main/CustomEntities.tsx#L57 it should be `if (dialogOpen || numChanges > 0) {`

2024-08-30 09:12 UTC, proddy commented on interface/src/app/status/SystemLog.tsx
> -    immediate: true,
good catch. That must be a bug in Alova - I'll report it.

2024-08-30 09:13 UTC, proddy commented
> And @MichaelDvP I got the same Network Error when uploading using the DragNDrop so will try and fix that too next

Think I fixed it.

2024-08-30 09:20 UTC, proddy commented
> A lot of changes. I have not checked all. Appart from the not working log i've found: (not part of this PR)
> 
> * the divider in settings, is it intended? https://github.com/proddy/EMS-ESP32/blob/41ec9162fda52b033a4202f459a7c3ad75e506f3/interface/src/app/settings/Settings.tsx#L134
> * custom entity adding/editing is still reversed by autoupdate. In this line https://github.com/proddy/EMS-ESP32/blob/41ec9162fda52b033a4202f459a7c3ad75e506f3/interface/src/app/main/CustomEntities.tsx#L57 it should be `if (dialogOpen || numChanges > 0) {`

The divider in Settings was intentional as Upload/Download wasn't really a 'Settings'. But I'll remove it as it does look strange.

2024-08-30 11:23 UTC, MichaelDvP commented
Compiled with version set to 3.7.0-dev31. The update-button with link to 3.7.0.dev-32 is shown, but clicking does only a restart.

2024-08-30 12:40 UTC, MichaelDvP commented
Hm, status page is workingagain, it was blocked by the update process. 
Log from terminal: repeated every few milliseconds: `Firmware upload failed - HTTP code 4294967295`

2024-08-30 13:00 UTC, proddy commented
> damn. both those are bugs - I'll fix

fixed. hopefully.

2024-08-30 13:42 UTC, MichaelDvP commented
For me the download did not start, i tested on a esp32-16M without PSRAM, so also no https. 
This stops here https://github.com/proddy/EMS-ESP32/blob/71d90d6416ea257846d992b09b93e7898ab4fd89/src/system.cpp#L1877
but the function just returned false, but does not set `upload_status(false);`, so the upload functions is called every main loop, blocking the status page, there was no reboot at all.
I modufied to 
```
    if (httpCode != HTTP_CODE_OK) {
        LOG_ERROR("Firmware download %s failed - HTTP code %u", saved_url.c_str(), httpCode);
        EMSESP::system_.upload_status(false);
        saved_url.clear(); // prevent from downloading again
        return false;
    }
```
and the log is one line:
`2024-08-30 15:33:56.264 E 16: [system] Firmware download https://github.com/emsesp/EMS-ESP32/releases/download/v3.6.5/EMS-ESP-3_6_5-ESP32-16MB.bin failed - HTTP code 4294967295`
and emsesp keeps responsible.

If i change the url to http:// the http-return is http:301

2024-08-30 14:23 UTC, MichaelDvP commented
Update with a ESP32S3-16M+ is working. But webpage is instantly redirected to dashboard while update is working in the background.

2024-08-30 14:38 UTC, proddy commented
> Update with a ESP32S3-16M+ is working. But webpage is instantly redirected to dashboard while update is working in the background.

yes, fixed that. Will check-in shortly.

2024-08-31 07:32 UTC, MichaelDvP commented
The new dialogs look a bit odd to me.
old / new:
![grafik](https://github.com/user-attachments/assets/c75bafc7-5eea-4029-a2ac-84e4c65207e7)
![grafik](https://github.com/user-attachments/assets/cd8b26ab-770f-43cd-a289-89372263bd1d)

2024-08-31 10:42 UTC, proddy commented
> The new dialogs look a bit odd to me. old / new: ![grafik](https://private-user-images.githubusercontent.com/59284019/363396887-c75bafc7-5eea-4029-a2ac-84e4c65207e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDExNDIsIm5iZiI6MTcyNTEwMDg0MiwicGF0aCI6Ii81OTI4NDAxOS8zNjMzOTY4ODctYzc1YmFmYzctNWVlYS00MDI5LWEyYWMtODRlNGM2NTIwN2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEwNDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZjExN2VjOWQzOWQzZWQ0NGJlYjkxODJhNGI1ZjUyNDQyYTZlMjZkMWM2MjllYWNmY2M3ZmZlOGViYWEwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SfhDH1nnCqYc-bV20U9Bw9JZ52KqoLJ4guQJV9MTwyU) ![grafik](https://private-user-images.githubusercontent.com/59284019/363396895-cd8b26ab-770f-43cd-a289-89372263bd1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDExNDIsIm5iZiI6MTcyNTEwMDg0MiwicGF0aCI6Ii81OTI4NDAxOS8zNjMzOTY4OTUtY2Q4YjI2YWItNzcwZi00M2NkLWEyODktODkzNzIyNjNiZDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEwNDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZjhkMTY5NWI2YmQ1NDc0ODA3Nzk1ODBkNWIyYjQ2MWExNGZmYzdhZThjMjE1M2EzOTdhYjM0ZmViZTMzZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5R7dfPAx6_PB6PyzmQv2xC01r-wQvuEqtEcAxFy3MGk)

it's the new Grid component. The box resizes and is responsive. Before those text boxes were too large (e.g. a DeviceID is not 40 chars long). What do you think we should change to make it look nicer?

2024-08-31 14:21 UTC, proddy commented
Another 50 files changed, sorry. I think you just need to check the behaviour when EMS-ESP is restarted and what happens when you click on Install

2024-09-01 06:43 UTC, MichaelDvP commented
The new restart monitor looks really nice.
Automatic install still does not work on systems without psram (missing https) and failed download from github result in a loop.
I suggest to change emsesp.cpp lines 1676-1678 to
```
    } else if (!system_.uploadFirmwareURL()) { // start an upload from a URL. This is blocking.
        system_.upload_status(false);
    }
```
to stop retrying the GET endless.

The get result is HTTP code 4294967295, or code 301 if i set the url to http://. 
If there is no way to download the bin from github via http, i suggest to remove the install button on systems without psram.

2024-09-01 08:12 UTC, proddy commented
> The new restart monitor looks really nice. Automatic install still does not work on systems without psram (missing https) and failed download from github result in a loop. I suggest to change emsesp.cpp lines 1676-1678 to
> 
> ```
>     } else if (!system_.uploadFirmwareURL()) { // start an upload from a URL. This is blocking.
>         system_.upload_status(false);
>     }
> ```
> 
> to stop retrying the GET endless.
> 
> The get result is HTTP code 4294967295, or code 301 if i set the url to http://. If there is no way to download the bin from github via http, i suggest to remove the install button on systems without psram.

Thanks. What I could also do is check if the URL is valid in the Web code and if not, hide the button as you suggested.

I also found some other errors I made in the upload and restart, so will fix those now too.

2024-09-01 08:38 UTC, MichaelDvP commented
> What I could also do is check if the URL is valid in the Web code and if not, hide the button as you suggested.

Yes, but the https:// link is valid and the browser can resolve it, but ems-esp-tasmota builds  can not access it. 
For http://  we get 301, checking in terminal with curl it redirects to https.:
```
> GET /emsesp/EMS-ESP32/releases/download/v3.6.5/EMS-ESP-3_6_5-ESP32-16MB.bin HTTP/1.1
< HTTP/1.1 301 Moved Permanently
< Location: https://github.com/emsesp/EMS-ESP32/releases/download/v3.6.5/EMS-ESP-3_6_5-ESP32-16MB.bin
```
Maybe for this cases replace the install button by a download-button.

2024-09-01 11:14 UTC, proddy commented
> > What I could also do is check if the URL is valid in the Web code and if not, hide the button as you suggested.
> 
> Yes, but the https:// link is valid and the browser can resolve it, but ems-esp-tasmota builds can not access it. For http:// we get 301, checking in terminal with curl it redirects to https.:
> 
> ```
> > GET /emsesp/EMS-ESP32/releases/download/v3.6.5/EMS-ESP-3_6_5-ESP32-16MB.bin HTTP/1.1
> < HTTP/1.1 301 Moved Permanently
> < Location: https://github.com/emsesp/EMS-ESP32/releases/download/v3.6.5/EMS-ESP-3_6_5-ESP32-16MB.bin
> ```
> 
> Maybe for this cases replace the install button by a download-button.

The HTTPClient call fails and returns -1. I suspect it's because the Tasmota platform has mbed SSL removed which is needed. I'll see if I can find a workaround, otherwise as you said, disabled auto-download for Tasmota builds.

2024-09-01 11:16 UTC, mattreim commented
Update German translation: 

```lua
  WAIT_FIRMWARE: 'Die Firmware wird hochgeladen und installiert', 

  RESTARTING_PRE: 'Initialisierung', 
  RESTARTING_POST: 'Neuladen' 

```

2024-09-01 14:19 UTC, proddy commented
@MichaelDvP okay to merge and fix things as we find them?

2024-09-01 14:41 UTC, MichaelDvP commented
>  Tasmota have their own light HTTPClient library but i couldn't see how they got around not using SSL, so gave up. 

Afair it's a adapted version of BearSSL.
> okay to merge and fix things as we find them?

Have not completly checked the latest changes, but all i've tested works well now, i think it's ok to merge.

2024-09-01 15:17 UTC, MichaelDvP commented
![grafik](https://github.com/user-attachments/assets/a89a7281-aae9-49c2-849f-75dc00b2ba1f)

Download link points the the stable version. I think in case of running the latest version it's better to link to the download page https://github.com/emsesp/EMS-ESP32/releases and let the user decide which version he wants.

2024-09-01 18:37 UTC, proddy commented
> ![grafik](https://private-user-images.githubusercontent.com/59284019/363501290-a89a7281-aae9-49c2-849f-75dc00b2ba1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMTQ4NDcsIm5iZiI6MTcyNTIxNDU0NywicGF0aCI6Ii81OTI4NDAxOS8zNjM1MDEyOTAtYTg5YTcyODEtYWFlOS00OWMyLTg0OWYtNzVkYzAwYjJiYTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE4MTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzFiMmMwYzU3NDc0MzJhMDAyMTdiYzkwNTExMDIxZTgwN2MwMzcxNDAwMDkwZGYyMGE4ZjY5NmQwYWNlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Rgp9xjePM_bhSX1YIMeO5tgJ12-XAsR2_8BmwLQm6k)
> 
> Download link points the the stable version. I think in case of running the latest version it's better to link to the download page https://github.com/emsesp/EMS-ESP32/releases and let the user decide which version he wants.

That was a bug. Hopefully fixed now.

2024-09-01 18:38 UTC, merged