wwFlowTempOffset for UBAParameterWWPlus (RC310)
emsesp/EMS-ESP32 pull request #510
Opened 2022-05-18 16:18 UTC by tp1de

2022-05-19 17:57 UTC, MichaelDvP requested changes

2022-05-20 09:13 UTC, MichaelDvP approved these changes

2022-05-20 10:35 UTC, merged

2022-05-20 10:35 UTC, proddy commented
really nice @tp1de - great to see more people understanding the somewhat complex code and extending it. welcome to the team!

2022-05-20 10:46 UTC, tp1de commented
more to come .....